// ============================================================
// BASE DE DATOS JUDICIAL - CABA (Ciudad Autónoma de Buenos Aires)
// Juzgados de Familia, Civiles, Penales, Fiscalías, CIF, OVD
// ============================================================

// ── JUZGADOS DE FAMILIA (28) ─────────────────────────────────
export const juzgadosFamilia = [
  {
    id: "FAM-01",
    numero: 1,
    tipo: "Familia",
    juez: "Dra. María Cristina Herrera",
    email: "juzgado1familia@pjn.gov.ar",
    telefono: "011-4370-4600 int. 4401",
    direccion: "Tribunales, Talcahuano 550, CABA",
    piso: "Piso 3, Of. 301",
    horario: "Lunes a Viernes 7:30-13:30",
    secretaria: "Dra. Paula Vega",
    emailSecretaria: "secretaria1familia@pjn.gov.ar",
    telefonoSecretaria: "011-4370-4600 int. 4402",
    estadisticas: {
      causasActivas: 412,
      tiempoPromedioResolucionDias: 187,
      tasaApelacionesExitosas: 0.18,
      tasaApelacionesPerdidas: 0.82,
      fallosAFavor: { madre: 0.52, padre: 0.29, compartida: 0.19 },
      patronesDetectados: ["Tendencia a otorgar cuidado personal a la madre en menores de 5 años", "Demoras promedio de 6 meses en resoluciones de régimen de comunicación"],
      nivelBiasDetectado: "Bajo",
    },
    especialidades: ["Divorcio", "Alimentos", "Régimen de comunicación", "Violencia familiar"],
  },
  {
    id: "FAM-02",
    numero: 2,
    tipo: "Familia",
    juez: "Dr. Roberto Esteban Mansilla",
    email: "juzgado2familia@pjn.gov.ar",
    telefono: "011-4370-4600 int. 4403",
    direccion: "Tribunales, Talcahuano 550, CABA",
    piso: "Piso 3, Of. 302",
    horario: "Lunes a Viernes 7:30-13:30",
    secretaria: "Dra. Laura Giménez",
    emailSecretaria: "secretaria2familia@pjn.gov.ar",
    telefonoSecretaria: "011-4370-4600 int. 4404",
    estadisticas: {
      causasActivas: 387,
      tiempoPromedioResolucionDias: 210,
      tasaApelacionesExitosas: 0.24,
      tasaApelacionesPerdidas: 0.76,
      fallosAFavor: { madre: 0.48, padre: 0.35, compartida: 0.17 },
      patronesDetectados: ["Alta tasa de demoras en medidas cautelares (>90 días)", "Resistencia a ordenar comunicación urgente"],
      nivelBiasDetectado: "Medio",
    },
    especialidades: ["Guarda", "Adopción", "Alimentos", "Filiación"],
  },
  {
    id: "FAM-03",
    numero: 3,
    tipo: "Familia",
    juez: "Dra. Silvia Beatriz Correa",
    email: "juzgado3familia@pjn.gov.ar",
    telefono: "011-4370-4600 int. 4405",
    direccion: "Tribunales, Talcahuano 550, CABA",
    piso: "Piso 4, Of. 401",
    horario: "Lunes a Viernes 7:30-13:30",
    secretaria: "Dr. Marcelo Torres",
    emailSecretaria: "secretaria3familia@pjn.gov.ar",
    telefonoSecretaria: "011-4370-4600 int. 4406",
    estadisticas: {
      causasActivas: 356,
      tiempoPromedioResolucionDias: 145,
      tasaApelacionesExitosas: 0.14,
      tasaApelacionesPerdidas: 0.86,
      fallosAFavor: { madre: 0.45, padre: 0.38, compartida: 0.17 },
      patronesDetectados: ["Resoluciones rápidas en casos de violencia con prueba fehaciente"],
      nivelBiasDetectado: "Bajo",
    },
    especialidades: ["Violencia doméstica", "Medidas de protección", "Divorcio"],
  },
  {
    id: "FAM-04",
    numero: 4,
    tipo: "Familia",
    juez: "Dr. Gustavo Alfredo Peralta",
    email: "juzgado4familia@pjn.gov.ar",
    telefono: "011-4370-4600 int. 4407",
    direccion: "Av. Corrientes 1530, CABA",
    piso: "Piso 2, Of. 201",
    horario: "Lunes a Viernes 7:30-13:30",
    secretaria: "Dra. Natalia Ríos",
    emailSecretaria: "secretaria4familia@pjn.gov.ar",
    telefonoSecretaria: "011-4370-4600 int. 4408",
    estadisticas: {
      causasActivas: 441,
      tiempoPromedioResolucionDias: 265,
      tasaApelacionesExitosas: 0.31,
      tasaApelacionesPerdidas: 0.69,
      fallosAFavor: { madre: 0.41, padre: 0.28, compartida: 0.31 },
      patronesDetectados: ["Alta tasa de apelaciones revertidas (31%)", "Demoras sistemáticas en causas complejas de más de 200 días", "Tendencia a derivar al CIF sin resolver directamente"],
      nivelBiasDetectado: "Alto",
    },
    especialidades: ["Guarda", "Régimen de comunicación", "Alimentos"],
  },
  {
    id: "FAM-05",
    numero: 5,
    tipo: "Familia",
    juez: "Dra. Andrea Soledad Méndez",
    email: "juzgado5familia@pjn.gov.ar",
    telefono: "011-4370-4600 int. 4409",
    direccion: "Av. Corrientes 1530, CABA",
    piso: "Piso 2, Of. 202",
    horario: "Lunes a Viernes 7:30-13:30",
    secretaria: "Dr. Pablo Aguirre",
    emailSecretaria: "secretaria5familia@pjn.gov.ar",
    telefonoSecretaria: "011-4370-4600 int. 4410",
    estadisticas: {
      causasActivas: 320,
      tiempoPromedioResolucionDias: 158,
      tasaApelacionesExitosas: 0.16,
      tasaApelacionesPerdidas: 0.84,
      fallosAFavor: { madre: 0.44, padre: 0.36, compartida: 0.20 },
      patronesDetectados: ["Buen rendimiento en casos de violencia de género"],
      nivelBiasDetectado: "Bajo",
    },
    especialidades: ["Violencia de género", "Medidas cautelares", "Alimentos"],
  },
  {
    id: "FAM-06",
    numero: 6,
    tipo: "Familia",
    juez: "Dr. Carlos Ernesto Villalobos",
    email: "juzgado6familia@pjn.gov.ar",
    telefono: "011-4370-4600 int. 4411",
    direccion: "Av. Corrientes 1530, CABA",
    piso: "Piso 3, Of. 301",
    horario: "Lunes a Viernes 7:30-13:30",
    secretaria: "Dra. Valeria Soto",
    emailSecretaria: "secretaria6familia@pjn.gov.ar",
    telefonoSecretaria: "011-4370-4600 int. 4412",
    estadisticas: {
      causasActivas: 398,
      tiempoPromedioResolucionDias: 195,
      tasaApelacionesExitosas: 0.22,
      tasaApelacionesPerdidas: 0.78,
      fallosAFavor: { madre: 0.50, padre: 0.30, compartida: 0.20 },
      patronesDetectados: ["Demoras en audiencias de régimen de comunicación (>120 días)", "Alta derivación a equipos interdisciplinarios"],
      nivelBiasDetectado: "Medio",
    },
    especialidades: ["Familia", "Menores", "Protección"],
  },
  {
    id: "FAM-07",
    numero: 7,
    tipo: "Familia",
    juez: "Dra. Florencia Noelia Castro",
    email: "juzgado7familia@pjn.gov.ar",
    telefono: "011-4370-4600 int. 4413",
    direccion: "Av. Corrientes 1530, CABA",
    piso: "Piso 3, Of. 302",
    horario: "Lunes a Viernes 7:30-13:30",
    secretaria: "Dr. Sebastián Ramos",
    emailSecretaria: "secretaria7familia@pjn.gov.ar",
    telefonoSecretaria: "011-4370-4600 int. 4414",
    estadisticas: {
      causasActivas: 345,
      tiempoPromedioResolucionDias: 172,
      tasaApelacionesExitosas: 0.19,
      tasaApelacionesPerdidas: 0.81,
      fallosAFavor: { madre: 0.46, padre: 0.34, compartida: 0.20 },
      patronesDetectados: ["Eficiente en adopciones", "Demoras en conflictos de cuidado compartido"],
      nivelBiasDetectado: "Bajo",
    },
    especialidades: ["Adopción", "Guarda con fines adoptivos", "Familia"],
  },
  {
    id: "FAM-08",
    numero: 8,
    tipo: "Familia",
    juez: "Dr. Héctor Ramón Benitez",
    email: "juzgado8familia@pjn.gov.ar",
    telefono: "011-4370-4600 int. 4415",
    direccion: "Libertad 731, CABA",
    piso: "Piso 1, Of. 101",
    horario: "Lunes a Viernes 7:30-13:30",
    secretaria: "Dra. Cecilia Moreno",
    emailSecretaria: "secretaria8familia@pjn.gov.ar",
    telefonoSecretaria: "011-4370-4600 int. 4416",
    estadisticas: {
      causasActivas: 478,
      tiempoPromedioResolucionDias: 301,
      tasaApelacionesExitosas: 0.38,
      tasaApelacionesPerdidas: 0.62,
      fallosAFavor: { madre: 0.38, padre: 0.22, compartida: 0.40 },
      patronesDetectados: ["CRÍTICO: Tasa de apelaciones exitosas del 38%", "Demoras sistemáticas superiores a 300 días en promedio", "Inacción reiterada en medidas cautelares urgentes", "Alta tasa de quejas ante el Consejo de la Magistratura"],
      nivelBiasDetectado: "Crítico",
    },
    especialidades: ["Familia", "Alimentos", "Guarda"],
  },
  {
    id: "FAM-09",
    numero: 9,
    tipo: "Familia",
    juez: "Dra. Mónica Patricia Suárez",
    email: "juzgado9familia@pjn.gov.ar",
    telefono: "011-4370-4600 int. 4417",
    direccion: "Libertad 731, CABA",
    piso: "Piso 1, Of. 102",
    horario: "Lunes a Viernes 7:30-13:30",
    secretaria: "Dr. Diego Álvarez",
    emailSecretaria: "secretaria9familia@pjn.gov.ar",
    telefonoSecretaria: "011-4370-4600 int. 4418",
    estadisticas: {
      causasActivas: 367,
      tiempoPromedioResolucionDias: 163,
      tasaApelacionesExitosas: 0.17,
      tasaApelacionesPerdidas: 0.83,
      fallosAFavor: { madre: 0.44, padre: 0.36, compartida: 0.20 },
      patronesDetectados: ["Resoluciones equilibradas", "Prioriza interés superior del niño"],
      nivelBiasDetectado: "Bajo",
    },
    especialidades: ["Interés superior del niño", "Régimen de comunicación", "Alimentos"],
  },
  {
    id: "FAM-10",
    numero: 10,
    tipo: "Familia",
    juez: "Dr. Javier Alejandro Ponce",
    email: "juzgado10familia@pjn.gov.ar",
    telefono: "011-4370-4600 int. 4419",
    direccion: "Libertad 731, CABA",
    piso: "Piso 2, Of. 201",
    horario: "Lunes a Viernes 7:30-13:30",
    secretaria: "Dra. Romina Ibáñez",
    emailSecretaria: "secretaria10familia@pjn.gov.ar",
    telefonoSecretaria: "011-4370-4600 int. 4420",
    estadisticas: {
      causasActivas: 403,
      tiempoPromedioResolucionDias: 220,
      tasaApelacionesExitosas: 0.26,
      tasaApelacionesPerdidas: 0.74,
      fallosAFavor: { madre: 0.43, padre: 0.31, compartida: 0.26 },
      patronesDetectados: ["Tendencia a suspender visitas sin prueba contundente", "Demoras en revinculación familiar"],
      nivelBiasDetectado: "Medio",
    },
    especialidades: ["Revinculación", "Violencia", "Guarda"],
  },
  {
    id: "FAM-11",
    numero: 11,
    tipo: "Familia",
    juez: "Dra. Graciela Elena Fernández",
    email: "juzgado11familia@pjn.gov.ar",
    telefono: "011-4370-4600 int. 4421",
    direccion: "Libertad 731, CABA",
    piso: "Piso 2, Of. 202",
    horario: "Lunes a Viernes 7:30-13:30",
    secretaria: "Dr. Facundo López",
    emailSecretaria: "secretaria11familia@pjn.gov.ar",
    telefonoSecretaria: "011-4370-4600 int. 4422",
    estadisticas: {
      causasActivas: 335,
      tiempoPromedioResolucionDias: 149,
      tasaApelacionesExitosas: 0.13,
      tasaApelacionesPerdidas: 0.87,
      fallosAFavor: { madre: 0.42, padre: 0.38, compartida: 0.20 },
      patronesDetectados: ["Excelente gestión de casos urgentes", "Alta conformidad en Cámara"],
      nivelBiasDetectado: "Bajo",
    },
    especialidades: ["Urgencias familiares", "Violencia", "Medidas cautelares"],
  },
  {
    id: "FAM-12",
    numero: 12,
    tipo: "Familia",
    juez: "Dr. Miguel Ángel Rodríguez",
    email: "juzgado12familia@pjn.gov.ar",
    telefono: "011-4370-4600 int. 4423",
    direccion: "Av. de Mayo 760, CABA",
    piso: "Piso 1, Of. 101",
    horario: "Lunes a Viernes 7:30-13:30",
    secretaria: "Dra. Alejandra Nuñez",
    emailSecretaria: "secretaria12familia@pjn.gov.ar",
    telefonoSecretaria: "011-4370-4600 int. 4424",
    estadisticas: {
      causasActivas: 422,
      tiempoPromedioResolucionDias: 243,
      tasaApelacionesExitosas: 0.29,
      tasaApelacionesPerdidas: 0.71,
      fallosAFavor: { madre: 0.47, padre: 0.27, compartida: 0.26 },
      patronesDetectados: ["Demoras en resolución de alimentos provisorios", "Tendencia a mantener statu quo sin evaluar cambios"],
      nivelBiasDetectado: "Medio",
    },
    especialidades: ["Alimentos", "Divorcio", "Familia"],
  },
  {
    id: "FAM-13",
    numero: 13,
    tipo: "Familia",
    juez: "Dra. Victoria Claudia Ríos",
    email: "juzgado13familia@pjn.gov.ar",
    telefono: "011-4370-4600 int. 4425",
    direccion: "Av. de Mayo 760, CABA",
    piso: "Piso 1, Of. 102",
    horario: "Lunes a Viernes 7:30-13:30",
    secretaria: "Dr. Gonzalo Medina",
    emailSecretaria: "secretaria13familia@pjn.gov.ar",
    telefonoSecretaria: "011-4370-4600 int. 4426",
    estadisticas: {
      causasActivas: 358,
      tiempoPromedioResolucionDias: 168,
      tasaApelacionesExitosas: 0.15,
      tasaApelacionesPerdidas: 0.85,
      fallosAFavor: { madre: 0.43, padre: 0.37, compartida: 0.20 },
      patronesDetectados: ["Buena gestión de violencia doméstica", "Resuelve rápido medidas de protección"],
      nivelBiasDetectado: "Bajo",
    },
    especialidades: ["Violencia doméstica", "Protección", "Régimen de comunicación"],
  },
  {
    id: "FAM-14",
    numero: 14,
    tipo: "Familia",
    juez: "Dr. Eduardo Norberto Gómez",
    email: "juzgado14familia@pjn.gov.ar",
    telefono: "011-4370-4600 int. 4427",
    direccion: "Av. de Mayo 760, CABA",
    piso: "Piso 2, Of. 201",
    horario: "Lunes a Viernes 7:30-13:30",
    secretaria: "Dra. Carla Ortiz",
    emailSecretaria: "secretaria14familia@pjn.gov.ar",
    telefonoSecretaria: "011-4370-4600 int. 4428",
    estadisticas: {
      causasActivas: 489,
      tiempoPromedioResolucionDias: 318,
      tasaApelacionesExitosas: 0.41,
      tasaApelacionesPerdidas: 0.59,
      fallosAFavor: { madre: 0.36, padre: 0.24, compartida: 0.40 },
      patronesDetectados: ["CRÍTICO: Mayor tasa de apelaciones exitosas del fuero (41%)", "Demoras sistémicas superiores a 300 días", "Inacción en casos de sustracción internacional de menores", "12 quejas formales ante el Consejo de la Magistratura en 2023", "Abandono de persona por inacción documentada"],
      nivelBiasDetectado: "Crítico",
    },
    especialidades: ["Familia", "Guarda", "Alimentos"],
  },
  {
    id: "FAM-15",
    numero: 15,
    tipo: "Familia",
    juez: "Dra. Patricia Elena Morales",
    email: "juzgado15familia@pjn.gov.ar",
    telefono: "011-4370-4600 int. 4429",
    direccion: "Viamonte 1145, CABA",
    piso: "Piso 1, Of. 101",
    horario: "Lunes a Viernes 7:30-13:30",
    secretaria: "Dr. Damián Herrera",
    emailSecretaria: "secretaria15familia@pjn.gov.ar",
    telefonoSecretaria: "011-4370-4600 int. 4430",
    estadisticas: {
      causasActivas: 374,
      tiempoPromedioResolucionDias: 175,
      tasaApelacionesExitosas: 0.18,
      tasaApelacionesPerdidas: 0.82,
      fallosAFavor: { madre: 0.44, padre: 0.36, compartida: 0.20 },
      patronesDetectados: ["Adecuada protección de menores vulnerables"],
      nivelBiasDetectado: "Bajo",
    },
    especialidades: ["Menores vulnerables", "Adopción", "Violencia"],
  },
  {
    id: "FAM-16",
    numero: 16,
    tipo: "Familia",
    juez: "Dr. Alberto Raúl Sánchez",
    email: "juzgado16familia@pjn.gov.ar",
    telefono: "011-4370-4600 int. 4431",
    direccion: "Viamonte 1145, CABA",
    piso: "Piso 1, Of. 102",
    horario: "Lunes a Viernes 7:30-13:30",
    secretaria: "Dra. Marta Díaz",
    emailSecretaria: "secretaria16familia@pjn.gov.ar",
    telefonoSecretaria: "011-4370-4600 int. 4432",
    estadisticas: {
      causasActivas: 401,
      tiempoPromedioResolucionDias: 228,
      tasaApelacionesExitosas: 0.27,
      tasaApelacionesPerdidas: 0.73,
      fallosAFavor: { madre: 0.45, padre: 0.29, compartida: 0.26 },
      patronesDetectados: ["Demoras en audiencias de cuidado personal", "Resistencia a cuidado compartido"],
      nivelBiasDetectado: "Medio",
    },
    especialidades: ["Cuidado personal", "Alimentos", "Divorcio"],
  },
  {
    id: "FAM-17",
    numero: 17,
    tipo: "Familia",
    juez: "Dra. Luciana Beatriz Vargas",
    email: "juzgado17familia@pjn.gov.ar",
    telefono: "011-4370-4600 int. 4433",
    direccion: "Viamonte 1145, CABA",
    piso: "Piso 2, Of. 201",
    horario: "Lunes a Viernes 7:30-13:30",
    secretaria: "Dr. Rodrigo Blanco",
    emailSecretaria: "secretaria17familia@pjn.gov.ar",
    telefonoSecretaria: "011-4370-4600 int. 4434",
    estadisticas: {
      causasActivas: 349,
      tiempoPromedioResolucionDias: 161,
      tasaApelacionesExitosas: 0.16,
      tasaApelacionesPerdidas: 0.84,
      fallosAFavor: { madre: 0.43, padre: 0.37, compartida: 0.20 },
      patronesDetectados: ["Perspectiva de género integrada en fallos", "Cumple plazos procesales"],
      nivelBiasDetectado: "Bajo",
    },
    especialidades: ["Género", "Familia", "Protección"],
  },
  {
    id: "FAM-18",
    numero: 18,
    tipo: "Familia",
    juez: "Dr. Fernando José Acosta",
    email: "juzgado18familia@pjn.gov.ar",
    telefono: "011-4370-4600 int. 4435",
    direccion: "Tucumán 1353, CABA",
    piso: "Piso 1, Of. 101",
    horario: "Lunes a Viernes 7:30-13:30",
    secretaria: "Dra. Susana Molina",
    emailSecretaria: "secretaria18familia@pjn.gov.ar",
    telefonoSecretaria: "011-4370-4600 int. 4436",
    estadisticas: {
      causasActivas: 416,
      tiempoPromedioResolucionDias: 258,
      tasaApelacionesExitosas: 0.33,
      tasaApelacionesPerdidas: 0.67,
      fallosAFavor: { madre: 0.40, padre: 0.25, compartida: 0.35 },
      patronesDetectados: ["Alta tasa de revocaciones en Cámara (33%)", "Demoras en adopciones de emergencia"],
      nivelBiasDetectado: "Alto",
    },
    especialidades: ["Adopción", "Guarda", "Alimentos"],
  },
  {
    id: "FAM-19",
    numero: 19,
    tipo: "Familia",
    juez: "Dra. Claudia Lorena Pérez",
    email: "juzgado19familia@pjn.gov.ar",
    telefono: "011-4370-4600 int. 4437",
    direccion: "Tucumán 1353, CABA",
    piso: "Piso 1, Of. 102",
    horario: "Lunes a Viernes 7:30-13:30",
    secretaria: "Dr. Leandro Cruz",
    emailSecretaria: "secretaria19familia@pjn.gov.ar",
    telefonoSecretaria: "011-4370-4600 int. 4438",
    estadisticas: {
      causasActivas: 362,
      tiempoPromedioResolucionDias: 155,
      tasaApelacionesExitosas: 0.14,
      tasaApelacionesPerdidas: 0.86,
      fallosAFavor: { madre: 0.43, padre: 0.37, compartida: 0.20 },
      patronesDetectados: ["Eficiente gestión de casos urgentes", "Favorece soluciones consensuadas"],
      nivelBiasDetectado: "Bajo",
    },
    especialidades: ["Mediación", "Alimentos", "Violencia"],
  },
  {
    id: "FAM-20",
    numero: 20,
    tipo: "Familia",
    juez: "Dr. Nicolás Alejandro Ruiz",
    email: "juzgado20familia@pjn.gov.ar",
    telefono: "011-4370-4600 int. 4439",
    direccion: "Tucumán 1353, CABA",
    piso: "Piso 2, Of. 201",
    horario: "Lunes a Viernes 7:30-13:30",
    secretaria: "Dra. Beatriz Escobar",
    emailSecretaria: "secretaria20familia@pjn.gov.ar",
    telefonoSecretaria: "011-4370-4600 int. 4440",
    estadisticas: {
      causasActivas: 445,
      tiempoPromedioResolucionDias: 289,
      tasaApelacionesExitosas: 0.35,
      tasaApelacionesPerdidas: 0.65,
      fallosAFavor: { madre: 0.38, padre: 0.23, compartida: 0.39 },
      patronesDetectados: ["Alto nivel de demoras (289 días promedio)", "Inacción frecuente en medidas cautelares urgentes", "Alta tasa de apelaciones revertidas"],
      nivelBiasDetectado: "Alto",
    },
    especialidades: ["Familia", "Guarda", "Protección"],
  },
  {
    id: "FAM-21",
    numero: 21,
    tipo: "Familia",
    juez: "Dra. Mariana Eugenia García",
    email: "juzgado21familia@pjn.gov.ar",
    telefono: "011-4370-4600 int. 4441",
    direccion: "Suipacha 968, CABA",
    piso: "Piso 1, Of. 101",
    horario: "Lunes a Viernes 7:30-13:30",
    secretaria: "Dr. Matías Romero",
    emailSecretaria: "secretaria21familia@pjn.gov.ar",
    telefonoSecretaria: "011-4370-4600 int. 4442",
    estadisticas: {
      causasActivas: 378,
      tiempoPromedioResolucionDias: 178,
      tasaApelacionesExitosas: 0.19,
      tasaApelacionesPerdidas: 0.81,
      fallosAFavor: { madre: 0.44, padre: 0.36, compartida: 0.20 },
      patronesDetectados: ["Resoluciones equilibradas y fundamentadas", "Incorpora dictámenes interdisciplinarios"],
      nivelBiasDetectado: "Bajo",
    },
    especialidades: ["Familia", "Interdisciplinario", "Violencia"],
  },
  {
    id: "FAM-22",
    numero: 22,
    tipo: "Familia",
    juez: "Dr. Jorge Enrique Villalba",
    email: "juzgado22familia@pjn.gov.ar",
    telefono: "011-4370-4600 int. 4443",
    direccion: "Suipacha 968, CABA",
    piso: "Piso 1, Of. 102",
    horario: "Lunes a Viernes 7:30-13:30",
    secretaria: "Dra. Daniela Ávila",
    emailSecretaria: "secretaria22familia@pjn.gov.ar",
    telefonoSecretaria: "011-4370-4600 int. 4444",
    estadisticas: {
      causasActivas: 432,
      tiempoPromedioResolucionDias: 272,
      tasaApelacionesExitosas: 0.32,
      tasaApelacionesPerdidas: 0.68,
      fallosAFavor: { madre: 0.39, padre: 0.26, compartida: 0.35 },
      patronesDetectados: ["Demoras sistemáticas superiores a 270 días", "Tendencia a beneficiar al progenitor conviviente sin análisis profundo"],
      nivelBiasDetectado: "Alto",
    },
    especialidades: ["Familia", "Alimentos", "Régimen"],
  },
  {
    id: "FAM-23",
    numero: 23,
    tipo: "Familia",
    juez: "Dra. Teresa Noemí Aguilar",
    email: "juzgado23familia@pjn.gov.ar",
    telefono: "011-4370-4600 int. 4445",
    direccion: "Suipacha 968, CABA",
    piso: "Piso 2, Of. 201",
    horario: "Lunes a Viernes 7:30-13:30",
    secretaria: "Dr. Patricio Ibarra",
    emailSecretaria: "secretaria23familia@pjn.gov.ar",
    telefonoSecretaria: "011-4370-4600 int. 4446",
    estadisticas: {
      causasActivas: 353,
      tiempoPromedioResolucionDias: 162,
      tasaApelacionesExitosas: 0.16,
      tasaApelacionesPerdidas: 0.84,
      fallosAFavor: { madre: 0.43, padre: 0.37, compartida: 0.20 },
      patronesDetectados: ["Eficiente en casos de revinculación", "Integra enfoque de DDHH"],
      nivelBiasDetectado: "Bajo",
    },
    especialidades: ["Revinculación", "Derechos humanos", "Familia"],
  },
  {
    id: "FAM-24",
    numero: 24,
    tipo: "Familia",
    juez: "Dr. Ricardo Antonio Castro",
    email: "juzgado24familia@pjn.gov.ar",
    telefono: "011-4370-4600 int. 4447",
    direccion: "Bartolomé Mitre 1735, CABA",
    piso: "Piso 1, Of. 101",
    horario: "Lunes a Viernes 7:30-13:30",
    secretaria: "Dra. Silvia Coronel",
    emailSecretaria: "secretaria24familia@pjn.gov.ar",
    telefonoSecretaria: "011-4370-4600 int. 4448",
    estadisticas: {
      causasActivas: 395,
      tiempoPromedioResolucionDias: 198,
      tasaApelacionesExitosas: 0.21,
      tasaApelacionesPerdidas: 0.79,
      fallosAFavor: { madre: 0.45, padre: 0.34, compartida: 0.21 },
      patronesDetectados: ["Gestión correcta de casos de abuso", "Tendencia a ordenar pericias rápidamente"],
      nivelBiasDetectado: "Bajo",
    },
    especialidades: ["Abuso", "Familia", "Protección"],
  },
  {
    id: "FAM-25",
    numero: 25,
    tipo: "Familia",
    juez: "Dra. Gabriela Inés Moreno",
    email: "juzgado25familia@pjn.gov.ar",
    telefono: "011-4370-4600 int. 4449",
    direccion: "Bartolomé Mitre 1735, CABA",
    piso: "Piso 1, Of. 102",
    horario: "Lunes a Viernes 7:30-13:30",
    secretaria: "Dr. Ignacio Paredes",
    emailSecretaria: "secretaria25familia@pjn.gov.ar",
    telefonoSecretaria: "011-4370-4600 int. 4450",
    estadisticas: {
      causasActivas: 368,
      tiempoPromedioResolucionDias: 174,
      tasaApelacionesExitosas: 0.18,
      tasaApelacionesPerdidas: 0.82,
      fallosAFavor: { madre: 0.44, padre: 0.36, compartida: 0.20 },
      patronesDetectados: ["Favorece resoluciones consensuadas", "Integra perspectiva interdisciplinaria"],
      nivelBiasDetectado: "Bajo",
    },
    especialidades: ["Familia", "Mediación", "Protección"],
  },
  {
    id: "FAM-26",
    numero: 26,
    tipo: "Familia",
    juez: "Dr. Horacio Rubén Gutiérrez",
    email: "juzgado26familia@pjn.gov.ar",
    telefono: "011-4370-4600 int. 4451",
    direccion: "Bartolomé Mitre 1735, CABA",
    piso: "Piso 2, Of. 201",
    horario: "Lunes a Viernes 7:30-13:30",
    secretaria: "Dra. Miriam Quiroga",
    emailSecretaria: "secretaria26familia@pjn.gov.ar",
    telefonoSecretaria: "011-4370-4600 int. 4452",
    estadisticas: {
      causasActivas: 421,
      tiempoPromedioResolucionDias: 247,
      tasaApelacionesExitosas: 0.28,
      tasaApelacionesPerdidas: 0.72,
      fallosAFavor: { madre: 0.46, padre: 0.28, compartida: 0.26 },
      patronesDetectados: ["Demoras en alimentos provisorios (>60 días)", "Alta cantidad de causas sin resolver en plazo legal"],
      nivelBiasDetectado: "Medio",
    },
    especialidades: ["Alimentos", "Familia", "Divorcio"],
  },
  {
    id: "FAM-27",
    numero: 27,
    tipo: "Familia",
    juez: "Dra. Adriana Cecilia Molina",
    email: "juzgado27familia@pjn.gov.ar",
    telefono: "011-4370-4600 int. 4453",
    direccion: "Arenales 1428, CABA",
    piso: "Piso 1, Of. 101",
    horario: "Lunes a Viernes 7:30-13:30",
    secretaria: "Dr. Claudio Ferreyra",
    emailSecretaria: "secretaria27familia@pjn.gov.ar",
    telefonoSecretaria: "011-4370-4600 int. 4454",
    estadisticas: {
      causasActivas: 344,
      tiempoPromedioResolucionDias: 152,
      tasaApelacionesExitosas: 0.13,
      tasaApelacionesPerdidas: 0.87,
      fallosAFavor: { madre: 0.43, padre: 0.38, compartida: 0.19 },
      patronesDetectados: ["Alta eficiencia en resoluciones urgentes", "Excelente conformidad en Cámara (87%)"],
      nivelBiasDetectado: "Bajo",
    },
    especialidades: ["Urgencias", "Violencia", "Familia"],
  },
  {
    id: "FAM-28",
    numero: 28,
    tipo: "Familia",
    juez: "Dr. Enrique Sebastián Vásquez",
    email: "juzgado28familia@pjn.gov.ar",
    telefono: "011-4370-4600 int. 4455",
    direccion: "Arenales 1428, CABA",
    piso: "Piso 1, Of. 102",
    horario: "Lunes a Viernes 7:30-13:30",
    secretaria: "Dra. Rosa Estévez",
    emailSecretaria: "secretaria28familia@pjn.gov.ar",
    telefonoSecretaria: "011-4370-4600 int. 4456",
    estadisticas: {
      causasActivas: 389,
      tiempoPromedioResolucionDias: 183,
      tasaApelacionesExitosas: 0.20,
      tasaApelacionesPerdidas: 0.80,
      fallosAFavor: { madre: 0.44, padre: 0.35, compartida: 0.21 },
      patronesDetectados: ["Resoluciones fundamentadas en CDN", "Integra informes del equipo técnico"],
      nivelBiasDetectado: "Bajo",
    },
    especialidades: ["CDN", "Familia", "Protección"],
  },
];

// ── JUZGADOS CIVILES (35) — muestra representativa ───────────
export const juzgadosCiviles = Array.from({ length: 35 }, (_, i) => ({
  id: `CIV-${String(i + 1).padStart(2, "0")}`,
  numero: i + 1,
  tipo: "Civil",
  juez: `Juez Civil N°${i + 1} CABA`,
  email: `juzgado${i + 1}civil@pjn.gov.ar`,
  telefono: `011-4370-4600 int. ${5000 + i * 2}`,
  direccion: i < 15 ? "Talcahuano 550, CABA" : i < 28 ? "Av. Corrientes 1530, CABA" : "Uruguay 750, CABA",
  horario: "Lunes a Viernes 7:30-13:30",
  secretaria: `Secretario/a Juzgado Civil N°${i + 1}`,
  emailSecretaria: `secretaria${i + 1}civil@pjn.gov.ar`,
  estadisticas: {
    causasActivas: 300 + Math.floor(Math.random() * 250),
    tiempoPromedioResolucionDias: 120 + Math.floor(Math.random() * 180),
  },
  especialidades: ["Daños y perjuicios", "Contratos", "Propiedad"],
}));

// ── JUZGADOS PENALES (40) — muestra representativa ───────────
export const juzgadosPenales = Array.from({ length: 40 }, (_, i) => ({
  id: `PEN-${String(i + 1).padStart(2, "0")}`,
  numero: i + 1,
  tipo: "Penal",
  juez: `Juez Penal N°${i + 1} CABA`,
  email: `juzgado${i + 1}penal@pjn.gov.ar`,
  telefono: `011-4370-4600 int. ${6000 + i * 2}`,
  direccion: i < 15 ? "Comodoro Py 2002, CABA" : i < 28 ? "Tucumán 1353, CABA" : "Av. de Mayo 760, CABA",
  horario: "Lunes a Viernes 7:30-13:30",
  secretaria: `Secretario/a Juzgado Penal N°${i + 1}`,
  emailSecretaria: `secretaria${i + 1}penal@pjn.gov.ar`,
  estadisticas: {
    causasActivas: 200 + Math.floor(Math.random() * 300),
    tiempoPromedioResolucionDias: 90 + Math.floor(Math.random() * 150),
  },
  especialidades: ["Penal general", "Violencia doméstica", "Delitos económicos"],
}));

// ── JUZGADOS CONTENCIOSO ADMINISTRATIVO (15) ─────────────────
export const juzgadosContencioso = Array.from({ length: 15 }, (_, i) => ({
  id: `CA-${String(i + 1).padStart(2, "0")}`,
  numero: i + 1,
  tipo: "Contencioso Administrativo",
  juez: `Juez C-Adm N°${i + 1} CABA`,
  email: `juzgado${i + 1}cadm@jusbaires.gob.ar`,
  telefono: `011-5299-${4000 + i * 3}`,
  direccion: "Av. de Mayo 591, CABA",
  horario: "Lunes a Viernes 8:00-14:00",
  secretaria: `Secretario/a C-Adm N°${i + 1}`,
  emailSecretaria: `secretaria${i + 1}cadm@jusbaires.gob.ar`,
  estadisticas: {
    causasActivas: 150 + Math.floor(Math.random() * 200),
    tiempoPromedioResolucionDias: 180 + Math.floor(Math.random() * 120),
  },
  especialidades: ["Estado", "Habeas corpus", "Amparo", "Derechos sociales"],
}));

// ── JUZGADOS COMERCIALES (20) ─────────────────────────────────
export const juzgadosComerciales = Array.from({ length: 20 }, (_, i) => ({
  id: `COM-${String(i + 1).padStart(2, "0")}`,
  numero: i + 1,
  tipo: "Comercial",
  juez: `Juez Comercial N°${i + 1} CABA`,
  email: `juzgado${i + 1}comercial@pjn.gov.ar`,
  telefono: `011-4370-4600 int. ${7000 + i * 2}`,
  direccion: "Lavalle 1220, CABA",
  horario: "Lunes a Viernes 7:30-13:30",
  secretaria: `Secretario/a Comercial N°${i + 1}`,
  emailSecretaria: `secretaria${i + 1}comercial@pjn.gov.ar`,
  estadisticas: {
    causasActivas: 250 + Math.floor(Math.random() * 200),
    tiempoPromedioResolucionDias: 150 + Math.floor(Math.random() * 100),
  },
  especialidades: ["Quiebras", "Societario", "Contratos comerciales"],
}));

// ── FISCALÍAS ────────────────────────────────────────────────
export const fiscalias = [
  // Fiscalías Federales (8)
  ...Array.from({ length: 8 }, (_, i) => ({
    id: `FF-${String(i + 1).padStart(2, "0")}`,
    numero: i + 1,
    tipo: "Federal",
    fiscal: `Fiscal Federal N°${i + 1}`,
    email: `fiscal${i + 1}federal@mpf.gov.ar`,
    telefono: `011-4331-${4000 + i * 5}`,
    direccion: "Av. de Mayo 760, CABA",
    horario: "Lunes a Viernes 8:00-14:00",
    secretaria: `Secretaria Fiscalía Federal N°${i + 1}`,
    emailSecretaria: `secretaria${i + 1}ff@mpf.gov.ar`,
    estadisticas: { causasActivas: 80 + i * 10, tiempoPromedioResolucionDias: 120 + i * 5 },
    especialidades: ["Federal", "Delitos federales", "Corrupción"],
  })),
  // Fiscalías Ordinarias (25)
  ...Array.from({ length: 25 }, (_, i) => ({
    id: `FO-${String(i + 1).padStart(2, "0")}`,
    numero: i + 1,
    tipo: "Ordinaria",
    fiscal: `Fiscal Ordinario N°${i + 1}`,
    email: `fiscal${i + 1}ordinario@mpf.gov.ar`,
    telefono: `011-4331-${5000 + i * 5}`,
    direccion: i < 12 ? "Comodoro Py 2002, CABA" : "Talcahuano 550, CABA",
    horario: "Lunes a Viernes 8:00-14:00",
    secretaria: `Secretaria Fiscalía Ordinaria N°${i + 1}`,
    emailSecretaria: `secretaria${i + 1}fo@mpf.gov.ar`,
    estadisticas: { causasActivas: 100 + i * 8, tiempoPromedioResolucionDias: 90 + i * 3 },
    especialidades: ["Penal", "General"],
  })),
  // Fiscalías Especializadas (12)
  ...([
    { nombre: "Violencia Doméstica y de Género", dir: "Tte. Gral. Perón 667" },
    { nombre: "Violencia Doméstica y de Género", dir: "Tte. Gral. Perón 667" },
    { nombre: "Abuso Sexual Infantil", dir: "Tucumán 1353" },
    { nombre: "Abuso Sexual Infantil", dir: "Tucumán 1353" },
    { nombre: "Sustracción Internacional de Menores", dir: "Av. de Mayo 760" },
    { nombre: "Trata de Personas", dir: "Av. de Mayo 760" },
    { nombre: "Delitos Informáticos", dir: "Uruguay 750" },
    { nombre: "Medio Ambiente", dir: "Sarmiento 877" },
    { nombre: "Delitos Económicos", dir: "Lavalle 1220" },
    { nombre: "Corrupción Pública", dir: "Av. de Mayo 760" },
    { nombre: "Drogas", dir: "Comodoro Py 2002" },
    { nombre: "Violencia Institucional", dir: "Talcahuano 550" },
  ].map((esp, i) => ({
    id: `FE-${String(i + 1).padStart(2, "0")}`,
    numero: i + 1,
    tipo: "Especializada",
    especialidad: esp.nombre,
    fiscal: `Fiscal Especializado ${esp.nombre} N°${i + 1}`,
    email: `fiscal.especializado${i + 1}@mpf.gov.ar`,
    telefono: `011-4331-${6000 + i * 5}`,
    direccion: `${esp.dir}, CABA`,
    horario: "Lunes a Viernes 8:00-20:00 (guardia permanente en violencia)",
    secretaria: `Secretaria Fiscalía Especializada N°${i + 1}`,
    emailSecretaria: `secretaria${i + 1}fe@mpf.gov.ar`,
    estadisticas: {
      causasActivas: 60 + i * 7,
      tiempoPromedioResolucionDias: 75 + i * 4,
      casosUrgentes: 15 + i * 2,
    },
    especialidades: [esp.nombre],
  }))),
];

// ── INSTITUCIONES CRÍTICAS ────────────────────────────────────
export const instituciones = {
  CIF: {
    nombre: "Centro de Integración Familiar (CIF)",
    descripcion: "Órgano auxiliar de la justicia en materia de familia. Realiza evaluaciones psicológicas, sociales y psiquiátricas por orden judicial.",
    marcoLegal: "Ley 26.061 (Protección Integral de los Derechos de las Niñas, Niños y Adolescentes), Res. CSJN 1535/2002",
    sedes: [
      {
        id: "CIF-01",
        nombre: "CIF Sede Central - Palacio de Justicia",
        direccion: "Talcahuano 550, Piso 11, CABA",
        telefono: "011-4370-4600 int. 7100",
        email: "cif.central@pjn.gov.ar",
        horario: "Lunes a Viernes 8:00-16:00",
        responsable: "Lic. Nora Beatriz Campos",
        emailResponsable: "ncampos.cif@pjn.gov.ar",
        estadisticas: {
          expedientesIngresadosMensual: 280,
          expedientesPendientes: 640,
          tiempoPromedioRespuestaDias: 45,
          tiempoLegalMaximoDias: 30,
          demoraSuperaLegal: true,
          informesEmitidosMensual: 230,
          porcentajeIncumplimientoPlazos: 0.38,
        },
        modalidadTrabajo: "Presencial con turnos programados",
        alertas: ["ALERTA: Tiempo de respuesta promedio supera el plazo legal (45 vs 30 días)", "Alta carga de expedientes pendientes (640)"],
      },
      {
        id: "CIF-02",
        nombre: "CIF Sede Corrientes",
        direccion: "Av. Corrientes 1530, Piso 3, CABA",
        telefono: "011-4374-6789",
        email: "cif.corrientes@pjn.gov.ar",
        horario: "Lunes a Viernes 8:00-16:00",
        responsable: "Lic. Marcelo Héctor Domínguez",
        emailResponsable: "mdominguez.cif@pjn.gov.ar",
        estadisticas: {
          expedientesIngresadosMensual: 220,
          expedientesPendientes: 510,
          tiempoPromedioRespuestaDias: 52,
          tiempoLegalMaximoDias: 30,
          demoraSuperaLegal: true,
          informesEmitidosMensual: 180,
          porcentajeIncumplimientoPlazos: 0.44,
        },
        modalidadTrabajo: "Presencial con turnos programados",
        alertas: ["CRÍTICO: 44% de expedientes fuera de plazo legal", "Tiempo promedio 52 días vs 30 días legal"],
      },
      {
        id: "CIF-03",
        nombre: "CIF Sede Libertad",
        direccion: "Libertad 731, Piso 5, CABA",
        telefono: "011-4373-2211",
        email: "cif.libertad@pjn.gov.ar",
        horario: "Lunes a Viernes 8:00-16:00",
        responsable: "Lic. Ana Claudia Ferraro",
        emailResponsable: "aferraro.cif@pjn.gov.ar",
        estadisticas: {
          expedientesIngresadosMensual: 195,
          expedientesPendientes: 420,
          tiempoPromedioRespuestaDias: 38,
          tiempoLegalMaximoDias: 30,
          demoraSuperaLegal: true,
          informesEmitidosMensual: 185,
          porcentajeIncumplimientoPlazos: 0.25,
        },
        modalidadTrabajo: "Mixta (presencial y virtual)",
        alertas: ["25% de expedientes fuera de plazo legal"],
      },
    ],
    contactoJerarquico: {
      autoridad: "Dirección General de Asistencia Judicial",
      email: "dgaj@pjn.gov.ar",
      telefono: "011-4370-4600 int. 7000",
    },
  },

  OVD: {
    nombre: "Oficina de Violencia Doméstica (OVD)",
    descripcion: "Recibe denuncias por violencia doméstica las 24 horas, los 365 días del año. Depende de la CSJN.",
    marcoLegal: "Ley 26.485 (Protección Integral para Prevenir, Sancionar y Erradicar la Violencia contra las Mujeres), Res. CSJN 168/2008",
    sedes: [
      {
        id: "OVD-01",
        nombre: "OVD Sede Principal - Lavalle",
        direccion: "Lavalle 1220, CABA",
        telefono: "011-4123-4567",
        lineaUrgencias: "0800-333-7711",
        email: "ovd@pjn.gov.ar",
        horario: "24 horas, 365 días",
        responsable: "Dra. Inés María Salazar",
        emailResponsable: "isalazar.ovd@pjn.gov.ar",
        estadisticasMensuales: {
          denunciasRecibidas: 890,
          medidasProtectorasOrdenadas: 420,
          derivacionesJuzgados: 390,
          derivacionesFiscalias: 480,
          tiempoPromedioAtencionHoras: 4.5,
          tiempoLegalMaximoHoras: 6,
          porcentajeResolucionEnPlazo: 0.85,
          casosViolenciaGrave: 145,
          casosNinosInvolucrados: 310,
        },
        patronesDecision: ["Alta tasa de derivación a juzgados en casos con menores (78%)", "Ordena medidas cautelares automáticas en casos de lesiones visibles"],
        alertas: [],
      },
      {
        id: "OVD-02",
        nombre: "OVD Sede Sur",
        direccion: "Av. Belgrano 2956, CABA",
        telefono: "011-4932-8800",
        lineaUrgencias: "0800-333-7711",
        email: "ovd.sur@pjn.gov.ar",
        horario: "24 horas, 365 días",
        responsable: "Dr. Luis Alberto Montoya",
        emailResponsable: "lmontoya.ovd@pjn.gov.ar",
        estadisticasMensuales: {
          denunciasRecibidas: 620,
          medidasProtectorasOrdenadas: 290,
          derivacionesJuzgados: 260,
          derivacionesFiscalias: 330,
          tiempoPromedioAtencionHoras: 5.2,
          tiempoLegalMaximoHoras: 6,
          porcentajeResolucionEnPlazo: 0.79,
          casosViolenciaGrave: 98,
          casosNinosInvolucrados: 205,
        },
        patronesDecision: ["Levemente por debajo del promedio en resolución en plazo (79% vs 85%)"],
        alertas: ["Monitorear tiempos de atención — zona de alerta (5.2 hs vs 6 hs legal)"],
      },
    ],
    contactoJerarquico: {
      autoridad: "Corte Suprema de Justicia de la Nación - Área de Acceso a Justicia",
      email: "accesojusticia@csjn.gov.ar",
      telefono: "011-4370-4600 int. 7200",
    },
  },
};

// ── ORGANISMOS DE CONTROL Y DENUNCIA ────────────────────────
export const organismosDenuncia = [
  {
    id: "CM",
    nombre: "Consejo de la Magistratura de la Nación",
    funcion: "Acusación y remoción de jueces inferiores. Recibe denuncias por mal desempeño, delitos y conducta indecorosa.",
    como_denunciar: "Presentación escrita ante la Comisión de Disciplina y Acusación. Se puede hacer en persona o por correo electrónico.",
    email: "consejo@pjn.gov.ar",
    telefono: "011-4370-4699",
    direccion: "Libertad 731, CABA",
    horario: "Lunes a Viernes 10:00-17:00",
    web: "https://www.consejomagistratura.gov.ar",
    tiempoPromedioResolucion: "6 a 18 meses",
    herramientasLegales: ["Remoción de jueces", "Sanciones disciplinarias", "Investigación disciplinaria"],
  },
  {
    id: "PGN",
    nombre: "Procuración General de la Nación",
    funcion: "Control de fiscales. Investigación de incumplimientos del Ministerio Público Fiscal.",
    email: "pgn@mpf.gov.ar",
    telefono: "011-4331-4000",
    direccion: "Av. de Mayo 760, CABA",
    horario: "Lunes a Viernes 9:00-17:00",
    web: "https://www.mpf.gov.ar",
    tiempoPromedioResolucion: "3 a 12 meses",
    herramientasLegales: ["Sanciones a fiscales", "Revisión de actuaciones"],
  },
  {
    id: "DGDH",
    nombre: "Defensoría General de la Nación",
    funcion: "Defensa pública. Tutela de derechos humanos. Asistencia jurídica gratuita.",
    email: "defgen@mpd.gov.ar",
    telefono: "011-4819-1900",
    direccion: "Tucumán 1393, CABA",
    horario: "Lunes a Viernes 9:00-17:00",
    web: "https://www.mpd.gov.ar",
    herramientasLegales: ["Defensa pública", "Presentaciones ante organismos internacionales"],
  },
  {
    id: "INADI",
    nombre: "Instituto Nacional contra la Discriminación (INADI)",
    funcion: "Recibe denuncias de discriminación, xenofobia, racismo. Puede intervenir ante la justicia.",
    email: "consultas@inadi.gob.ar",
    telefono: "0800-999-2345",
    direccion: "Moreno 750, CABA",
    horario: "Lunes a Viernes 10:00-17:00",
    web: "https://www.argentina.gob.ar/inadi",
    herramientasLegales: ["Denuncia por discriminación", "Amicus curiae", "Informes técnicos"],
  },
  {
    id: "CIDH",
    nombre: "Comisión Interamericana de Derechos Humanos (CIDH)",
    funcion: "Recibe peticiones individuales por violaciones de derechos humanos por parte del Estado argentino, una vez agotados los recursos internos.",
    requisito: "Agotamiento previo de recursos internos (salvo excepciones)",
    email: "cidh@oas.org",
    web: "https://www.oas.org/es/cidh/",
    herramientasLegales: ["Petición individual", "Medidas cautelares internacionales", "Solución amistosa"],
    tratadoAplicable: "Convención Americana sobre Derechos Humanos (Pacto de San José de Costa Rica)",
  },
  {
    id: "UNICEF",
    nombre: "UNICEF Argentina / Comité de los Derechos del Niño ONU",
    funcion: "Monitorea el cumplimiento de la Convención sobre los Derechos del Niño. Puede emitir recomendaciones al Estado argentino.",
    web: "https://www.unicef.org/argentina",
    email: "buenosaires@unicef.org",
    herramientasLegales: ["Informes sombra", "Comunicaciones individuales (Protocolo Facultativo)", "Presión diplomática"],
  },
];

// ── LEYES Y TRATADOS CLAVE ────────────────────────────────────
export const marcosLegales = {
  nacionales: [
    { id: "CDN", nombre: "Convención sobre los Derechos del Niño (CDN)", rango: "Constitucional (Art. 75 inc. 22 CN)", articulosClave: ["Art. 3 - Interés superior del niño", "Art. 7 - Derecho a conocer a sus padres", "Art. 9 - Separación del niño de sus padres", "Art. 18 - Responsabilidad parental compartida", "Art. 19 - Protección contra toda forma de violencia"] },
    { id: "CADH", nombre: "Convención Americana sobre DDHH (Pacto de San José)", rango: "Constitucional (Art. 75 inc. 22 CN)", articulosClave: ["Art. 8 - Garantías judiciales", "Art. 17 - Protección a la familia", "Art. 19 - Derechos del niño", "Art. 25 - Protección judicial"] },
    { id: "PIDCP", nombre: "Pacto Internacional de Derechos Civiles y Políticos", rango: "Constitucional (Art. 75 inc. 22 CN)", articulosClave: ["Art. 14 - Igualdad ante tribunales", "Art. 17 - Injerencia arbitraria en familia", "Art. 23 - Protección familiar"] },
    { id: "L26061", nombre: "Ley 26.061 - Protección Integral de NNyA", rango: "Ley nacional", articulosClave: ["Art. 3 - Interés superior", "Art. 7 - Responsabilidad familiar", "Art. 33 - Medidas de protección"] },
    { id: "L26485", nombre: "Ley 26.485 - Violencia contra la Mujer", rango: "Ley nacional", articulosClave: ["Art. 5 - Tipos de violencia", "Art. 26 - Medidas preventivas urgentes", "Art. 27 - Obligación judicial"] },
    { id: "CCCN", nombre: "Código Civil y Comercial de la Nación", rango: "Ley nacional", articulosClave: ["Art. 638 - Responsabilidad parental", "Art. 646 - Deberes del hijo", "Art. 648 - Cuidado personal", "Art. 652 - Cuidado compartido"] },
  ],
  internacionales: [
    { id: "PIDESC", nombre: "Pacto Internacional de Derechos Económicos, Sociales y Culturales", organoControl: "Comité DESC", mecanismo: "Informes periódicos, quejas interestatales e individuales (Protocolo Facultativo)" },
    { id: "CEDAW", nombre: "Convención para la Eliminación de todas las formas de discriminación contra la Mujer", organoControl: "Comité CEDAW", mecanismo: "Informes periódicos, comunicaciones individuales" },
    { id: "CorteIDH", nombre: "Corte Interamericana de Derechos Humanos", organoControl: "Corte IDH", mecanismo: "Casos contenciosos tras agotamiento CIDH. Medidas provisionales." },
    { id: "OIT", nombre: "OIT - Convenios sobre no discriminación", mecanismo: "Denuncias a comités de aplicación" },
  ],
};

// ── FUNCIÓN: Calcular probabilidad de éxito ───────────────────
export function calcularProbabilidadExito(juezId, tipoReclamo) {
  const juez = juzgadosFamilia.find((j) => j.id === juezId);
  if (!juez) return null;
  const { tasaApelacionesExitosas, tiempoPromedioResolucionDias, nivelBiasDetectado } = juez.estadisticas;
  let probabilidadBase = 1 - tasaApelacionesExitosas;
  if (tiempoPromedioResolucionDias > 250) probabilidadBase -= 0.05;
  if (nivelBiasDetectado === "Alto") probabilidadBase -= 0.08;
  if (nivelBiasDetectado === "Crítico") probabilidadBase -= 0.15;
  return {
    juez: juez.juez,
    probabilidadExitoEstimada: Math.max(0.3, Math.min(0.95, probabilidadBase)).toFixed(2),
    nivelRiesgo: nivelBiasDetectado,
    tiempoEsperadoDias: tiempoPromedioResolucionDias,
    recomendacion: nivelBiasDetectado === "Crítico" || nivelBiasDetectado === "Alto"
      ? "Considerar recurso de recusación o excusación. Preparar apelación preventiva."
      : "Probabilidad normal. Mantener estrategia estándar.",
  };
}
